insert into reacoes (descricao) values ("erupcao cutanea");
insert into reacoes (descricao) values ("lesao renal");
insert into reacoes (descricao) values ("anemia");
insert into reacoes (descricao) values ("nausea");
insert into reacoes (descricao) values ("constipacao");
insert into reacoes (descricao) values ("vomito");
insert into reacoes (descricao) values ("diarreia");
insert into reacoes (descricao) values ("prisao de ventre");
insert into reacoes (descricao) values ("fadiga");
insert into reacoes (descricao) values ("dores musculares");
insert into reacoes (descricao) values ("mal estar");
insert into reacoes (descricao) values ("disturbios visuais");
insert into reacoes (descricao) values ("tremor muscular");
insert into reacoes (descricao) values ("dificuldade na miccao");
insert into reacoes (descricao) values ("mudanca de humor");
